apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: payment
  labels:
    app: frontend
    tier: web
    project: payment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: payment
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: payment
    spec:
      containers:
      - name: frontend
        image: "joindevops/frontend:{{ .Values.deployment.imageVersion }}"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          # limits is greater than or equal to requests
          limits:
            cpu: 100m
            memory: 128Mi