apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: payment
spec:
    selector:
        app: frontend
        tier: web
        project: payment
    port:
    - name: fronend-ports
      protocol: TCP
      port: 80
      targetport: 80
    type: LoadBalancer